FROM ubuntu:18.04
ARG XNPM_READ_TOKEN_ARG
ENV XNPM_READ_TOKEN $XNPM_READ_TOKEN_ARG


RUN apt update && apt install -y nodejs npm 

WORKDIR /usr/src/app

COPY . .
RUN npm install
RUN chmod 777 /usr/src/app

EXPOSE 8001
EXPOSE 9873

CMD node /usr/src/app/src/main.js